steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/gen-spa-2:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/gen-spa-2:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gen-spa-2:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gen-spa-2',
      '--image', 'gcr.io/$PROJECT_ID/gen-spa-2:latest',
      '--platform', 'managed',
      '--region', 'asia-northeast1',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '300s',
      '--concurrency', '80',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production'
    ]

timeout: '1200s'  # 20分のタイムアウト

options:
  machineType: 'E2_HIGHCPU_8'  # ビルド用の高性能マシン