version: '3.8'

services:
  md-buddy-web-dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8082:8081"  # ホストの8082番ポート -> コンテナの8081番ポート
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    container_name: md-buddy-web-dev
    restart: unless-stopped