steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/weekend-getaway-planner:latest', '.']
  
  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/weekend-getaway-planner:latest']
  
  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/weekend-getaway-planner:latest'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=AIzaSyDvZa5QTmqdAB0do_K3W5NAeW6di69_3BI,GEMINI_MODEL=gemini-2.5-flash-lite-preview-06-17'

# ビルドしたイメージをartifactとして保存
images:
  - 'gcr.io/$PROJECT_ID/weekend-getaway-planner:latest'