steps:
  # ビルドステップ
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--no-cache'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tanren-repo/tanren-emotion-analysis:latest'
      - '.'

  # Artifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tanren-repo/tanren-emotion-analysis:latest'

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tanren-emotion-analysis'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tanren-repo/tanren-emotion-analysis:latest'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_AI_MODEL=gemini-2.5-pro-preview-05-06'
      - '--set-secrets'
      - 'GOOGLE_AI_API_KEY=tanren-gemini-api-key:latest'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tanren-repo/tanren-emotion-analysis:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'