name: Claude Code Action 実験

# 権限設定を追加
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: github.event.sender.type != 'Bot'
    
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude"
          timeout_minutes: 10
          allowed_tools: "Edit,Replace"
          custom_instructions: |
            あなたはTANREN株式会社のClaude Code Action実験プロジェクト専用アシスタントです。
            
            - 日本語で分かりやすく説明
            - 実験的な機能のテストサポート
            - コード改善提案
            - 簡潔で実用的なソリューション提供
