name: Claude 自動ドキュメント更新

# app/api/ 配下のファイルが変更されたら自動でREADMEを更新
on:
  pull_request:
    paths:
      - "app/api/**/*.ts"
      - "app/api/**/*.js"
      - "backend/**/*.py"

jobs:
  auto-update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            このPRでAPIエンドポイントに変更があります。

            以下の作業を実行してください：
            1. 変更されたAPIエンドポイントを分析
            2. README.mdのAPI仕様セクションを更新
            3. 新しいエンドポイントがあれば仕様書に追加
            4. 廃止されたエンドポイントがあれば削除または非推奨マーク

            ドキュメントは日本語で記載し、TANRENの開発者が理解しやすい形式にしてください。
