name: Claude Assistant (TANREN最適化版)

# PRコメント、Issue、レビューで @claude を呼び出すとClaude が応答
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-response:
    runs-on: ubuntu-latest

    # 書き込み権限のあるユーザーのみ実行可能（セキュリティ）
    if: github.event.sender.type != 'Bot'

    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          # AnthropicのAPIキー（GitHubシークレットから取得）
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Claudeのトリガーフレーズ（日本語でも @claude でもOK）
          trigger_phrase: "@claude"

          # 実行タイムアウト（最大30分）
          timeout_minutes: 30

          # 使用可能ツール（TANREN開発に特化）
          allowed_tools: "Bash(npm install),Bash(npm run test),Bash(npm run build),Bash(pnpm install),Bash(pnpm test),Bash(docker compose up -d),Edit,Replace"

          # 使用禁止ツール（セキュリティ対策）
          disallowed_tools: "TaskOutput,KillTask"

          # TANREN向けカスタム指示
          custom_instructions: |
            あなたはTANREN株式会社のプロジェクト（vibe-coding）専用のアシスタントです。

            技術スタック:
            - Next.js + React + TypeScript
            - Tailwind CSS + shadcn/ui
            - Docker + Cloud Run
            - Supabase（オプション）

            開発方針:
            - 美観 > 性能 > 開発速度
            - 日本語での応答・説明
            - モノレポ構造（apps/, packages/）
            - Conventional Commits

            UI/UX要件:
            - shadcn/ui + lucide-react使用
            - 2XL radius、グリッド設計
            - Core Web Vitals 75パーセンタイル以上

            コミットメッセージ例:
            - feat(app/image-generator): 画像アップロードUIを追加
            - fix(backend/api): 認証タイムアウトを修正

            必ず日本語で応答し、佐藤様のワークフローに最適化したソリューションを提案してください。
